### ISSUE TITLE
Feature: More than one fee per product

### ISSUE THREAD

**Issue by ghost** [WPprodigy/WooCommerce-Product-Fees#10]
Hi all, can you have more than one fee per product?

**Comment by WPprodigy** [comment]
Not at the moment, but I could perhaps add that into the next version

**Comment by ghost** [comment]
OK, sounds good.

Steven Walsh
Architect for Business

architectforbusiness.com
steve@architectforbusiness.com
(860) 510-9328

**Comment by jacobw201** [comment]
Hi Caleb! Just want to add my support to this idea. Multiple fees per product would provide a supremely elegant solution to a rather complex problem we have with our store :)

**Comment by st0nys** [comment]
Hi, first i want to say thank you for this really usefull plugin and i want add my support to this idea ! Multiple fees per product will allow me to add them in different languages, do you think it will be available soon or you didn't work on this project anymore ?

**Comment by WPprodigy** [comment]
> Multiple fees per product will allow me to add them in different languages

I'm not sure this feature would solve the problem you are having. All the fees would show up, regardless of language.

**Comment by margoreyfman** [comment]
To have more than one fee per product would great!!! Also adding additional fee that client can check or uncheck!

**Comment by WPprodigy** [comment]
> Also adding additional fee that client can check or uncheck!

That would be more along the lines of what this extension offers: https://woocommerce.com/products/woocommerce-checkout-add-ons/

**Comment by WPprodigy** [comment]
I've decided this is a bit out of scope for this plugin right now.

**Comment by youngjc345** [comment]
I would also like this feature, I hope you change your mind

**Comment by doowahdesign** [comment]
Would love to have more than one product fee in the next update!
