### ISSUE TITLE
Feature: Remove fees if local pickup (shipping) is selected

### ISSUE THREAD

**Issue by crowerks** [WPprodigy/WooCommerce-Product-Fees#13]
I am using product fees to add in additional shipping/handling fees per variation. I need these to not be added if someone selects "Local Pickup". Seems like a basic task - just don't know the best method to accomplish. An additional concern is "Free Shipping" - system still needs to calc and add fees if free shipping is added by a coupon. Thanks in advance!

**Comment by WPprodigy** [comment]
You should be able to hook into this: https://github.com/WPprodigy/woocommerce-product-fees/blob/master/classes/class-woocommerce-product-fees.php#L74, and conditionally remove the fees if local pickup is selected.

**Comment by crowerks** [comment]
Excellent, thanks! I'll give that a go - thanks again for the direction.
