### ISSUE TITLE
Explore possibility of allowing 100% off coupons to remove fees

### ISSUE THREAD

**Issue by WPprodigy** [WPprodigy/WooCommerce-Product-Fees#14]

**Comment by fmendoza** [comment]
Any update on this?

**Comment by WPprodigy** [comment]
Added this feature here: https://github.com/WPprodigy/woocommerce-product-fees/commit/e41011e76fef8e50b29f834a78923ca9698c9418

![](http://cld.wthms.co/eb4klf+)
