### ISSUE TITLE
Feature: Make it possible to apply the fees cost in a future day

### ISSUE THREAD

**Issue by ventouris** [WPprodigy/WooCommerce-Product-Fees#15]
I want to add a "Security Deposit" on my rental website. I want to do the following:

Example 1:

Product, Rental Cost: 100$, Security Deposit: 20$.

User pay the 100$ and the deposit a week before the actual rental.

Example 2:

Product 1, Rental Cost: 80$, Security Deposit: 15$
Product 2, Rental Cost: 100$, Security Deposit: 20$

User pay 80+100=180$ and first deposit 1 week before the rental date of product 1 and second deposit 1 week before the rental date of product 2.

**Comment by WPprodigy** [comment]
Would need something like Deposits or Subscriptions for this.
- https://woocommerce.com/products/woocommerce-subscriptions/
- https://woocommerce.com/products/woocommerce-deposits/
