### ISSUE TITLE
Feature: limit fees for specific countries

### ISSUE THREAD

**Issue by LyonBeton** [WPprodigy/WooCommerce-Product-Fees#16]
Hello,

I'm looking for a solution to manage the Eco Participation Taxe.
It's a taxe only used in France (I guess). 
It's a fix amount for each product (furniture).
This plugin could solve my problem if I could limit these taxe for France only.

Thank you

**Comment by kleinermann** [comment]
This would be very useful to me as well. I need to add a product disposal tax which only needs to be applied if sold in a certain country.
Did anybody look into implementing this feature yet?

**Comment by WPprodigy** [comment]
This is a bit out of the scope of this plugin's intention. You should look into using the actual tax functionality for this, or plugin's that extend taxes.
