### ISSUE TITLE
Feature: bulk upload with a csv file

### ISSUE THREAD

**Issue by LyonBeton** [WPprodigy/WooCommerce-Product-Fees#17]
Hello,

I think that all is on the title.
It could be great to have an option to update all products fees by uploading a csv files.
What do you think?

**Comment by WPprodigy** [comment]
Should be able to already do this with the existing product csv import plugins :)

Just include the meta fields of product-fee-name, product-fee-amount, and product-fee-multiplier if necessary when importing/updating products via csv.
