### ISSUE TITLE
Compatibility with WMCL

### ISSUE THREAD

**Issue by Ogien** [WPprodigy/WooCommerce-Product-Fees#18]
Currently the plugin reads all fees as just a number with no base currency. If I were to change the base to KRW (South Korean Won), the fees would just adopt the new currency symbol with no change in value.

It would be great for the plugin to recognize the base value of the store currency and use it against wcml. Naturally, WCML would understand that the base, was ie USD, and convert it to KRW; providing the proper symbol and price.

WCML --> WooCommerce Multilingual via https://wpml.org/documentation/related-projects/woocommerce-multilingual/

**Comment by WPprodigy** [comment]
I don't have any experience adding WPML support like this, but it's my understanding that the WPML plugin has to add compatibility, not the other way around.

> the fees would just adopt the new currency symbol with no change in value.

That is how WC core works by default on all pricing fields as well. If I need to pass a special parameter when adding the fees for WPML to use, then I can do that. But I'm not aware of anything that I need to do.

Whatever they did for this plugin: https://woocommerce.com/products/woocommerce-checkout-add-ons/, is probably the solution for this issue as well.
