### ISSUE TITLE
Not an issue as much as a question...

### ISSUE THREAD

**Issue by twistedjinn** [WPprodigy/WooCommerce-Product-Fees#20]
I'm using a bulk editing plugin and I was wondering what the custom fields are for the product fee name and amount? I tried searching though the code and found product_fee_name[1317] might have the numbers wrong here but I tried to use that and it couldn't find anything.

**Comment by WPprodigy** [comment]
The custom field names are: `product-fee-name`, `product-fee-amount`, and `product-fee-multiplier`.

The numbers in brackets will be there when using fees on a per-variation basis.
