### ISSUE TITLE
Issue with subscription

### ISSUE THREAD

**Issue by stickypages** [WPprodigy/WooCommerce-Product-Fees#22]
It looks like in the code that subscriptions will work, from what I can see. 
But I get ZERO fee added to the subscription total. 

It is in the "meta" for the subscription. But I cannot see any fee applied to the actual total. 

Any thoughts on this?

**Comment by WPprodigy** [comment]
What Subscriptions plugin are you using? What types of products are in the cart, and is this happening on the first purchase of the subs product, or on subsequent renewals?

**Comment by stickypages** [comment]
I'm using WooCommerce Subscriptions (by woo themes). 
I'm using a variable subscription, which is a renewal. 

You can see it works for a 'product', but not the recurring totals.

**Comment by stickypages** [comment]
Here is a screenshot
![2017-02-23 23_45_45-cart](https://cloud.githubusercontent.com/assets/658488/23294845/4cd6bdba-fa22-11e6-8278-c9192f3b18a1.png)

**Comment by WPprodigy** [comment]
Right, it isn't currently set up to add fees onto recurring totals. Will only add fees to the order one time.

Adding support for recurring costs may require a bit of work.

**Comment by stickypages** [comment]
Oh really eh. Thought I saw it was setup for some Subscription stuff in the code. 
Possible to get that implemented? I am desperate. I can't seem to quite grasp what is needed to do it myself yet. Still doing research...

**Comment by WPprodigy** [comment]
I don't have time to implement this right now, but I can maybe help point you in the right direction.

For Subscriptions, a one-time fee is already supported with the "sign up fee" option. So you only need to handle the recurring fee part. In **woocommerce-subscriptions/includes/class-wc-subscriptions-checkout.php**, there is a `woocommerce_add_order_fee_meta` hook that looks to be what you should use for this.

**Comment by stickypages** [comment]
Great thanks, will look into this some more. It would be a great addition when you have time !

**Comment by WPprodigy** [comment]
Oh hey, fixed this while fixing https://github.com/WPprodigy/woocommerce-product-fees/issues/23 :). Fees are now applied to recurring totals as well. 

![](http://cld.wthms.co/rpMYv+)

At first I thought about an extra setting on Subscription product to enable/disable this, but changed my mind. If somebody doesn't want recurring fees, they can just use the "sign up fee" option.

**Comment by stickypages** [comment]
Awesome, thanks!
