### ISSUE TITLE
WooCommerce 3.0 compatibility

### ISSUE THREAD

**Issue by maxrice** [WPprodigy/WooCommerce-Product-Fees#24]
Needs a few small changes:

- Replace `woocommerce_product_write_panels` with `woocommerce_product_data_panels` action on [this line](https://github.com/WPprodigy/woocommerce-product-fees/blob/v1.2/classes/admin/class-wcpf-admin-product-settings.php#L21).

- Replace the `WC_Product::$price` property usage [here](https://github.com/WPprodigy/woocommerce-product-fees/blob/v1.2/classes/class-woocommerce-product-fees.php#L64) and [here](https://github.com/WPprodigy/woocommerce-product-fees/blob/v1.2/classes/class-woocommerce-product-fees.php#L69) with `WC_Product::get_price()` method.

**Comment by WPprodigy** [comment]
Thanks :)

**Comment by raselahmed7** [comment]
First change is ok. But second change is confusing. 

On line# [64](https://github.com/WPprodigy/woocommerce-product-fees/blob/v1.2/classes/class-woocommerce-product-fees.php#L64) & [69](https://github.com/WPprodigy/woocommerce-product-fees/blob/v1.2/classes/class-woocommerce-product-fees.php#L69) `$values['data']->price` should be replace with `$values['data']->get_price()`

**Comment by WPprodigy** [comment]
Fixed with https://github.com/WPprodigy/woocommerce-product-fees/pull/25
