### ISSUE TITLE
How I can add the amount and name of the fee in the product page?

### ISSUE THREAD

**Issue by profesoryeow** [WPprodigy/WooCommerce-Product-Fees#27]
Hello Sr.
First: Thanks for your great plugin  WooCommerce Product Fees. I'm start to work in a small travel agency and your plugin is great because all travels have different tax/fees (is not fixed or percent).. so your plugin is great.

I'm a designer and i don't know a lot of woocommerce. I would like to ask you if can help me for show the custom fees i load with your plugin, not only in the checkout, also in the product page.

Thanks for your time and sorry for my bad English. Regards from Argentina.
Also i send you an email. Thanks again.

_PD: I practically use variable products_

**Comment by WPprodigy** [comment]
This isn't possible to do by default. You can get the fee name and amount using https://developer.wordpress.org/reference/functions/get_post_meta/, but you'll need to edit template files.

If you aren't comfortable with custom code, I would recommend just writing the fee information manually in the product short description.
