### ISSUE TITLE
Hide data if field is empty

### ISSUE THREAD

**Issue by kleinermann** [WPprodigy/WooCommerce-Product-Fees#31]
The product fee is always displayed in the cart even if i don't enter any data.
This only happens since i downloaded the latest version on GitHub.
![screenshot_1088](https://user-images.githubusercontent.com/846292/28561798-101ac838-7120-11e7-8d98-06efd6e79649.jpg)
![screenshot_1089](https://user-images.githubusercontent.com/846292/28561836-46b6a27c-7120-11e7-9a9d-036cacd20b01.jpg)

**Comment by WPprodigy** [comment]
Sorry, introduced a bug in https://github.com/WPprodigy/woocommerce-product-fees/commit/4ce7703dcfc3a09e8ec093376f3a06186a615130#diff-d2b5fd6dbde39d42d322b3b8706416c6. Fixed with https://github.com/WPprodigy/woocommerce-product-fees/commit/5a323326eb1e9d4ff1cc53ceda1386c526f680e0
