### ISSUE TITLE
Export Orders plugin is not showing the product fee 

### ISSUE THREAD

**Issue by agneszan** [WPprodigy/WooCommerce-Product-Fees#32]
Hello,I have a problem which is very important.
After someone buys a product they also pay the product fees .
I need to see the product fee after i export it to CSV
Can someone help me ? 

Thank You

**Comment by WPprodigy** [comment]
How are you exporting the orders, which plugin?

Don't want to just "pass blame", but this plugin is just adding fees that are built in to WooCommerce core. So it seems to me that your export plugin doesn't support a core WooCommerce feature.

**Comment by agneszan** [comment]
Hello , i dont know which plugin is the problem here , my client is using
woocommerce smart export  ( i will test this with different exports plugins
and see ).

I have a second issue now , i just updated product fees from GitHub and now
i see the Fee 0$ to all products , it was perfect before updating .
Can you help me fix this ? Thank you .

**Comment by WPprodigy** [comment]
Did you update the plugin on your website with the download from GH, or did you download from GH and then press update in WordPress?

What version does the plugin say on your site right now?

**Comment by agneszan** [comment]
Hello , Used the files from GH  . The version now is Version 1.3.0-beta |
By Caleb Burks <http://calebburks.com/> .

Also i tested with diferrent export orders and its just not working .
The export plugin is this
https://wordpress.org/plugins/woo-order-export-lite/
Export orders with date from today and the product fee is just not showing
in the order CSV file.

Thank You

**Comment by agneszan** [comment]
Are you testing checking ? Thank You

**Comment by WPprodigy** [comment]
I'll do some testing later today if I have some time. In the mean time, disable all plugins except for WooCommerce and Product fees to see if the error still occurs.

Also, try creating a new test product with fees.

**Comment by agneszan** [comment]
I disabled other plugins  and tested , the fees works fine , but now it
shows in all the products  without me to set it inside the product .

Maybe there is some IF condition somewhere in your code that does this with
the fee to show 0 in all products.

So there are 2 issues  :

1 -- it shows FEE 0 to all products without me to set it .
2-- After order is being complete , the fee which was paid its not showing
in any export orders  CSV file .

Thank You.

**Comment by agneszan** [comment]
and by FEE 0 euro to all products , i meant , no matter which one you add
to cart , it shows FEE 0

**Comment by agneszan** [comment]
so 1 product has a fee called plastic box of 1 euro , the others has no fee
value written .
and i get this in checkout .

SUBTOTAL €50.00
PLASTIC BOX €1.00
FEE €0.00  - THIS here is the problem , it was not here before update
TOTAL *€51.00*

**Comment by WPprodigy** [comment]
Do any of the other products in the cart have a fee value or name written in them? Leave the fields completely blank.

**Comment by agneszan** [comment]
No , all others are empty value the default you created

**Comment by agneszan** [comment]
no matter which one i added in cart it always shows FEE 0  and the one i
add ( if any value is added in product fee )

**Comment by agneszan** [comment]
Hi,have you looked into it ? thank you.

**Comment by agneszan** [comment]
Hello ?

**Comment by WPprodigy** [comment]
Sorry.  Looks like I introduced a bug in https://github.com/WPprodigy/woocommerce-product-fees/commit/4ce7703dcfc3a09e8ec093376f3a06186a615130#diff-d2b5fd6dbde39d42d322b3b8706416c6.

Fixed with the latest change: https://github.com/WPprodigy/woocommerce-product-fees/commit/5a323326eb1e9d4ff1cc53ceda1386c526f680e0
