### ISSUE TITLE
Multiple fees on one invoice do not show.

### ISSUE THREAD

**Issue by firstfilterservice** [WPprodigy/WooCommerce-Product-Fees#36]
Hello,

I’m having a problem that has only shown up recently.

If a customer has more than one item in their cart with a fee, only the first item in the cart has it’s fee applied. All of the other item fees are dropped. If you delete the first item from the cart, the new top item get’s it’s fee applied.

I have the WooCommerce -> Products -> Product Fees -> Fee Name Conflicts set to “Combine”. But in this case the fees have different names so it shouldn’t matter.

Any suggestions you have, I greatly appreciate. Thanks!

**Comment by WPprodigy** [comment]
Having trouble replicating this. Could you give a quick try of temporary deactivating all other plugins except for WC and Product Fees? Also switch to a default WordPress theme while testing.

Then once all is disabled, clear the cart and add the items again.

**Comment by firstfilterservice** [comment]
I tried disabling all the plugins except WooCommerce and ReallySimpleSSL (I think I need that one for my site to work). It didn't fix the problem. Then I tried using the TwentySeventeen theme, but it didn't fix it either.

The address to my site is: www.firstfilterservice.ca. 

I'm using your plugin for EHC (Enviro) fees on oil filters. There are 2 fees - short "EHC <8" (filters under 8" - for example B1441) and long "EHC >8" (filters 8" and over - for example BD7153).

If I add a B1441 to the cart first, I get the correct fee. 
If I then add a BD7153, it does not get a fee.
If I then delete the B1441, the fee changes to the correct amount.

If you need to log in to my site to poke around, I would be happy to provide you the login and password.

Thanks, Greg!

**Comment by WPprodigy** [comment]
Mm, could you try adding another letter to the fees? The only difference being a comparison operator could be the reasoning for this.

**Comment by firstfilterservice** [comment]
That fixed it!

No I just have to figure out how to update 4 or 5 thousand part numbers!

**Comment by WPprodigy** [comment]
The latest version does support product CSV importing/exporting. So could do a search/replace on the appropriate columns: https://docs.woocommerce.com/document/product-csv-importer-exporter/

Just delete everything but product ID, title, and the three columns for product fees. Then go from there in a search / replaces :)

**Comment by firstfilterservice** [comment]
That's what I ended up doing. I used the export/import function to replace all of my old fee names with simple "EHC Short" and "EHC Long." It seems to have corrected all of my issues. Thanks!
