### ISSUE TITLE
Product Fee not adjusting after updating item quantity on cart page

### ISSUE THREAD

**Issue by bordo78** [WPprodigy/WooCommerce-Product-Fees#37]
On the WooCommerce cart page, when you update the quantity of an item, the Product Fee does NOT recalculate. For example, I'm selling a $20 ticket with a 10% Product Fee, and the customer adds 2 tickets to their cart. When you initially get to the cart page, it correctly displays a subtotal of $40 and a Product Fee of $4. But when the quantity is increased to 3, the updated cart page shows a correct subtotal of $60, but the Product Fee stays at $4. Conversely, if decreased to 1, the subtotal is adjusted to $20, but the Product Fee again stays a $4. 

This is a **fatal** flaw as it allows the customer to add one ticket, then on the cart page, they can circumvent the Product Fee on additional tickets. Please fix. I'd like to use this plugin, but I cannot recommend it to my clients until this is resolved.

**Comment by WPprodigy** [comment]
I'm thinking there might be something else involved here, as I can't replicate this.

Could you temporarily disable all plugins except for WooCommerce core and Product Fees, then switch to a default WP theme as well while testing.

**Comment by bordo78** [comment]
I've left only WooCommerce core and Product Fees active...
![image](https://user-images.githubusercontent.com/38937658/39597312-d4e35676-4ec9-11e8-9bd6-9e8a19816835.png)

And I have the "2017" theme active...
![image](https://user-images.githubusercontent.com/38937658/39597343-ea05ef28-4ec9-11e8-87cd-01ca57ba3400.png)

And I have a product fee (i.e., 10% "Extra Fee") set for my widget...
![image](https://user-images.githubusercontent.com/38937658/39597405-1a985540-4eca-11e8-8261-0b2f80052366.png)

Onto testing: I added one widget to my cart and viewed my cart. Subtotal is $10, Extra Fee is $1...
![image](https://user-images.githubusercontent.com/38937658/39597458-50b898e2-4eca-11e8-9422-a163c2520587.png)
![image](https://user-images.githubusercontent.com/38937658/39597465-5b39de20-4eca-11e8-8f97-ff4d36ec5b49.png)

Now when I update the quantity to 4, subtotal is updated to $40, **Extra Fee is STILL $1**...
![image](https://user-images.githubusercontent.com/38937658/39597570-ba396148-4eca-11e8-8131-0e3be1ba1288.png)

**Comment by WPprodigy** [comment]
Need to use the "Multiply Fee by Quantity" setting.

**Comment by bordo78** [comment]
That fixed it. I missed that setting in my haste. My apologies, and thank you.

**Comment by WPprodigy** [comment]
All good :). The wording is a bit confusing when dealing with percentages.
