### ISSUE TITLE
Charging tax despite setting

### ISSUE THREAD

**Issue by scallemang** [WPprodigy/WooCommerce-Product-Fees#38]
Hi there,

I'm running this plugin on a client store – https://www.cameronsbrewing.com/shop/. Totals are looking good on the front end, however taxes are still being charged on the order itself. We're using the 'No taxes for fees' class. Should I switch to 'Zero rate' instead?

FWIW, we're using the Sripe plugin alone to handle payments. 

Any suggestion(s) how to fix this behaviour? 

Thank you!

**Comment by WPprodigy** [comment]
Hmm, not sure why that would be happening. I'll need to test a bit later.

But yea, try using the Zero Rate tax.

**Comment by torbentschechne** [comment]
Hello, I have a smiliar issue. I have a varitation with a 7% tax, and I set the product fee tax to the usual tax rate of 19%. But in the cart, the tax of the fee is charged with 7% and not 19%.

**Comment by WPprodigy** [comment]
I've not been able to replicate the original report. If prices in the backend are different than what is showing during checkout on the frontend, then there must be some other conflict occurring.

I do see what's happening in your scenario though @elbsurfer. "Fee tax based on the fee's product" setting isn't looking at the variation level, only the parent product. I'll get that fixed.

**Comment by WPprodigy** [comment]
Hmm, actually I can't replicate. Thought https://github.com/WPprodigy/woocommerce-product-fees/commit/cf7b42d149d291e9879654b3e50686224903d16f would help, but it's the same logic in the end :).

I tested a bunch of different tax classes / settings and the fee's tax class was always correct. Feel free to open up a new issue if you can replicate, just be sure to post all your current settings in relation to taxes and product fees.
