### ISSUE TITLE
 How to remove charges from the cart total

### ISSUE THREAD

**Issue by Guillaume72** [WPprodigy/WooCommerce-Product-Fees#41]
Very good plugin but I have a problem.
I use it to set up a deposit (for equipment rental) and I would not want the price to be included in the total of the basket. I just want the fee amount to appear as an indication. How to see the amount of fees (under the rate card for example) but that this amount is not calculated in the basket?
Thank you for your help

**Comment by WPprodigy** [comment]
I wouldn't recommend using the Fees API - this plugin isn't a good fit for that use case.

**Comment by Guillaume72** [comment]
Thank you for your reply. Yes I know that this plugin is not for ... but it largely corresponds to what I want to do. I was just thinking when adding code in function.php of my child theme to recalculate the basket by removing the value of the fees ... it could have worked.

**Comment by WPprodigy** [comment]
Yea, I get what you're thinking - it does make sense.

But it would ultimately be better to avoid messing with the calculations at all if the pricing is just for display. I'm not so sure showing a price in the "Order Totals" area would even be worth it. 

Something like [Product Add-Ons](https://www.woocommerce.com/products/product-add-ons/) might be good here. You could have a checkbox on the product page that says "I understand the $x.xx equipment rental deposit will be charged on visit", or something like that.
