### ISSUE TITLE
Taxes only calculating on the fee.

### ISSUE THREAD

**Issue by kdub718** [WPprodigy/WooCommerce-Product-Fees#42]
For some reason taxes on my site are only calculating based on the fee I entered not the actually product.  Any ideas?
![taxes](https://user-images.githubusercontent.com/19559355/47468317-7eb77100-d7af-11e8-8c9f-13360050bbaa.gif)

**Comment by kdub718** [comment]
This is still an issue for me.  Any support?

**Comment by WPprodigy** [comment]
If you aren't using the default "standard" tax class, then you need to assign your custom class to product: https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/

**Comment by kdub718** [comment]
Thanks for getting back to me.  I'm pretty sure I do have it setup that way.  Screen shots attached.
![taxes2](https://user-images.githubusercontent.com/19559355/47876036-6bbb2700-ddd5-11e8-8eb2-342774b76449.gif)
![taxes3](https://user-images.githubusercontent.com/19559355/47876037-6c53bd80-ddd5-11e8-939b-c3e75d56cd9c.gif)

**Comment by WPprodigy** [comment]
I'm thinking there is a problem with how you've listed cities. It would need to match exactly with how it's entered at checkout.

Try removing a city field for a tax row and see if it applies to the product then.

**Comment by kdub718** [comment]
They calculated fine before using the plugin.

But I'm totally open to trying anything.  Can you elaborate a little more by what you mean?  If I remove the city how will it calculate the right tax.  Is there a better way you suggest I should setup the taxes?

**Comment by kdub718** [comment]
I just updated my theme and it seems to be calculating now.  Thanks for getting back to me.

I'm still curious if you have any other suggestions for me on how to setup the taxes though.

**Comment by WPprodigy** [comment]
In the past when I debugged tax issues on sites, usually the "city" field was misunderstood / misused. If the customer doesn't enter the exact text for the city, then the rate won't match. I'd generally recommend using zip codes instead if possible.

Or perhaps even better - use Taxjar / Avalara extensions and let them handle taxes and reporting for you :)
