### ISSUE TITLE
fees disappear on the checkout page

### ISSUE THREAD

**Issue by fimskiy** [WPprodigy/WooCommerce-Product-Fees#43]
Please, help!
In the cart page fees are displayed, when i go to the checkout page fees disappear and the total amount changes.
I tried to change the theme for WordPress, disconnected the caching plugin – the problem remains.
(Woocommerce 3.5.1)

**Comment by WPprodigy** [comment]
I'm not able to replicate this. Try disabling all plugins except for WooCommerce and Product Fees and see if the issue goes away. then re-enable plugins one at a time until it comes back.
