### ISSUE TITLE
bulk edit product fees

### ISSUE THREAD

**Issue by paddy-mceneaney** [WPprodigy/WooCommerce-Product-Fees#48]
Hi I may have missed it, but is there a way to bulk edit the product fees for items that have been set via this plugin?

sorry if this is already implemented and I have missed it.

Thanks

Paddy

**Comment by WPprodigy** [comment]
There are no bulk editing fields, however there is support for the CSV export/importer.

So you could export your products to CSV. Then remove all fields except for ID, fee-name, fee-amount, etc and update as needed. Then re-import the CSV and choose to "merge existing products".
