### ISSUE TITLE
Feature request:display a products setup fee in the cart, next to the product 

### ISSUE THREAD

**Issue by paddy-mceneaney** [WPprodigy/WooCommerce-Product-Fees#51]
would it be possible to display a products setup fee in the cart, next to the product as well as the total fee at the end?

sorry about poor screen shot
![image](https://user-images.githubusercontent.com/2757788/69270039-1e6d4b80-0bca-11ea-849f-aabaedcfe36f.png)

**Comment by WPprodigy** [comment]
Not something that will likely be added to the plugin, but this can still be accomplished. Would need to:

1) Add a new row column here to the cart table: https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L33

2) Add the contents for this column: https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L124. Could look like this:

```
<td class="product-setup-fee" data-title="Setup Fee">
	<?php
		$fee_name   = get_post_meta( $product_id, 'product-fee-name', true );
		$fee_amount = get_post_meta( $product_id, 'product-fee-name', true );

		if ( 'Setup Fee' === $fee_name ) {
			echo esc_html( $fee_amount );
		}
	?>
</td>
```
