### ISSUE TITLE
Add option to make fees taxable

### ISSUE THREAD

**Issue by WPprodigy** [WPprodigy/WooCommerce-Product-Fees#7]
WooCommerce allows for making fees taxable under a certain tax class: https://github.com/woothemes/woocommerce/blob/df75d2f617dc37c5c2c172bdce3a2fd152017499/includes/class-wc-cart.php#L1917

Should add in a filter to enable taxes and define a tax class for fees.

**Comment by fran6666** [comment]
hi, i have the same request for taxes.

**Comment by WPprodigy** [comment]
@fran6666 Added with https://github.com/WPprodigy/woocommerce-product-fees/commit/b91b98cb4fc5f59bf769201eff5e97c90b528e1f. You can set the tax class you would like to use at WooCommerce > Settings > Products > Product Fees.
